# This is start

In [1]:
import numpy as np 

In [2]:
arr = np.array([[1,2,3,4,5]])

In [3]:
arr[0,1]

np.int64(2)

In [4]:
arr.shape

(1, 5)

In [5]:
arr.size

5

In [6]:
arr

array([[1, 2, 3, 4, 5]])

# Array creation : Conversion from other python structures

**From List**

In [7]:
listarr = np.array([[1,2,3,4,5],[11,22,33,44,55],[111,222,333,444,555]])

In [8]:
listarr

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  55],
       [111, 222, 333, 444, 555]])

In [9]:
listarr.ndim

2

In [10]:
listarr.dtype

dtype('int64')

In [11]:
listarr.shape

(3, 5)

In [12]:
listarr.size


15

In [13]:
listarr[2,4]

np.int64(555)

In [14]:
listarr[1,3]

np.int64(44)

In [15]:
listarr[1,4]=56

In [16]:
listarr

array([[  1,   2,   3,   4,   5],
       [ 11,  22,  33,  44,  56],
       [111, 222, 333, 444, 555]])

**From Zeros**

In [17]:
zeros = np.zeros((3,5))

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**From Arange**

In [19]:
range = np.arange(20)

In [20]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

*print element using indexing*

In [21]:
range[8]

np.int64(8)

In [22]:
range.shape

(20,)

In [23]:
range.size

20

**From linspace**

In [24]:
l = np.linspace(1,5,12)

In [25]:
l

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [26]:
l.ndim

1

**From Empty**

In [27]:
emp = np.empty((4,4))

In [28]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.86921686e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [29]:
e = np.empty_like(l)

In [30]:
e

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

**From identity**

In [31]:
id = np.identity(50)

In [32]:
id

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(50, 50))

In [33]:
id.shape

(50, 50)

In [34]:
id.size

2500

# Arraay Reshape

In [35]:
array = np.arange(99)

In [36]:
array=np.array(array)

In [37]:
array.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [38]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [40]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
array.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
array.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
srr = np.array(([1,2,3,4],[5,6,7,8]))

In [44]:
srr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
srr.size

8

In [46]:
srr.shape

(2, 4)

In [47]:
srr[1,2]=90

In [48]:
srr

array([[ 1,  2,  3,  4],
       [ 5,  6, 90,  8]])

In [49]:
srr.T

array([[ 1,  5],
       [ 2,  6],
       [ 3, 90],
       [ 4,  8]])

# Axis in numpy

In [50]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [51]:
arr =np.array(x)

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
arr.sum(axis=0)

array([12,  8,  9])

In [54]:
arr.sum(axis=1)

array([ 6, 15,  8])

*need to specific column sum*

In [55]:
np.sum(arr[:,1])

np.int64(8)

In [56]:
arr.flat

In [57]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [58]:
arr.ndim

2

In [59]:
arr.size

9

In [60]:
arr.shape

(3, 3)

In [61]:
arr.nbytes

72

In [62]:
arr.min(axis=0)

array([1, 1, 0])

In [63]:
arr.max(axis=1)

array([3, 6, 7])

In [64]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [65]:
arr.argmin()

np.int64(8)

In [66]:
arr.argmax()

np.int64(6)

In [67]:
vs=np.array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [68]:
vs.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
arr.argmin()

np.int64(8)

# Printing row and column 


In [71]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])

In [72]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

**print column**

In [73]:
print(arr[:,2])

[3 6 0]


**Print Row**

In [74]:
print(arr[2,:])

[7 1 0]


# maths operation in specific one column and row

In [75]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])

In [76]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

**Sum a spacific column**

In [77]:
np.sum(arr[:,1])

np.int64(8)

**Sum of spacific row**

In [78]:
np.sum(arr[2,:])

np.int64(8)

 # Maths Operations

In [79]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])

In [80]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [81]:
arr2=([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [82]:
arr+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [83]:
arr*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49,  1,  0]])

In [84]:
arr-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [85]:
arr.sum()

np.int64(29)

In [86]:
arr.mean()

np.float64(3.2222222222222223)

In [87]:
arr.std()

np.float64(2.2986845406196887)

In [88]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [89]:
arr.max()

np.int64(7)

In [90]:
np.max(arr)

np.int64(7)

In [91]:
np.exp(arr)


array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.71828183e+00, 1.00000000e+00]])

In [92]:
np.log(arr)

C:\Users\arunt\AppData\Local\Temp\ipykernel_7492\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 0.        ,       -inf]])

# Indexing & Sclicing

In [93]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])

In [94]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [95]:
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

***boolean indexing ,it give value b/w 2 given condition num***

In [96]:
arr[(arr>2)&(arr<5)]

array([3, 4])

In [97]:
arr[arr>5]


array([6, 7])

In [98]:
arr[arr<5]

array([1, 2, 3, 4, 1, 0])

***Fancy indexing ,when need to get specific row***

In [99]:
arr[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
arr[[1,2]]

array([[4, 5, 6],
       [7, 1, 0]])

In [101]:
arr[[2,0]]

array([[7, 1, 0],
       [1, 2, 3]])

# Joining and Spliting

In [102]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])

In [103]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [104]:
arr2=([[1, 2, 3],
       [4, 55, 6],
       [7, 1, 10]])

***Simple join***

In [105]:
np.concatenate([arr,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  1,  0],
       [ 1,  2,  3],
       [ 4, 55,  6],
       [ 7,  1, 10]])

***Vertical Join***

In [106]:
np.vstack([arr,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  1,  0],
       [ 1,  2,  3],
       [ 4, 55,  6],
       [ 7,  1, 10]])

*arr,arr* itself join

In [107]:
np.vstack([arr,arr])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

***Horizontal Join***

In [108]:
np.hstack([arr,arr2])

array([[ 1,  2,  3,  1,  2,  3],
       [ 4,  5,  6,  4, 55,  6],
       [ 7,  1,  0,  7,  1, 10]])

In [109]:
np.hstack([arr2,arr])

array([[ 1,  2,  3,  1,  2,  3],
       [ 4, 55,  6,  4,  5,  6],
       [ 7,  1, 10,  7,  1,  0]])

*arr,arr itself join*

In [110]:
np.hstack([arr,arr])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 1, 0, 7, 1, 0]])

**Split**

*using ravel() method**

In [111]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [112]:
np.split(arr,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 1, 0]])]

In [113]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

# Sorting & searching

In [130]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 1, 0]])

In [131]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

**Element sort**

In [133]:
np.sort(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [0, 1, 7]])

**index sort**

In [117]:
np.argsort(arr)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

**Where**

*it return index of given condition*

In [118]:
np.where(arr>5)

(array([1, 2]), array([2, 0]))

***Unique***

*it remove duplicates and give unique value*

In [119]:
np.unique(arr)

array([0, 1, 2, 3, 4, 5, 6, 7])

# Linear Algebra

In [120]:
arr= np.array([[1,2,3],[4,5,6],[7,1,0]])


In [121]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [122]:
arr2=([[1, 2, 3],
       [4, 55, 6],
       [7, 1, 10]])

**Dot product**

In [123]:
np.dot(arr,arr2)

array([[ 30, 115,  45],
       [ 66, 289, 102],
       [ 11,  69,  27]])

**Matmul**

In [124]:
np.matmul(arr,arr2)

array([[ 30, 115,  45],
       [ 66, 289, 102],
       [ 11,  69,  27]])

**Inverse**

In [125]:
np.linalg.inv(arr)

array([[ 0.4       , -0.2       ,  0.2       ],
       [-2.8       ,  1.4       , -0.4       ],
       [ 2.06666667, -0.86666667,  0.2       ]])

**Determinant**

In [126]:
np.linalg.det(arr)

np.float64(-15.0)

**Eigen value**

In [127]:
np.linalg.eig(arr)

EigResult(eigenvalues=array([ 9.11177374, -3.57256872,  0.46079498]), eigenvectors=array([[ 0.34708305,  0.36664943,  0.1540464 ],
       [ 0.86531637,  0.41256061, -0.83467399],
       [ 0.36160882, -0.83388365,  0.5287618 ]]))